resources:
  - name: aarch_64_Ubuntu_16_04_prep_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/aarch_64.Ubuntu_16.04.prep
      branch: master

  - name: aarch_reqProc_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: shippable/reqProc
      branch: master

  - name: aarch_execTemplates_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/execTemplates
      branch: master

  - name: aarch_64_micro_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: Shippable/micro
      branch: master

  - name: aarch_dh_cli
    type: cliConfig
    integration: ric03uec-dockerhub

  - name: aarch_bits_access_cli
    type: cliConfig
    integration: aws_bits_access
    pointer:
      region: us-east-1

  - name: aarch_bits_ecr_cli
    type: cliConfig
    integration: ecr_bits_push
    pointer:
      region: us-east-1

  - name: aarch_reqExec_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: shippable/reqExec
      branch: master

  - name: aarch64_u16_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: dry-dock/aarch64_u16
      branch: master

  - name: aarch64_u16_img
    type: image
    integration: shipDH
    pointer:
      sourceName: drydock/aarch64_u16
    seed:
      versionName: master

  - name: aarch64_u16all_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: dry-dock/aarch64_u16all
      branch: master

  - name: aarch64_u16all_img
    type: image
    integration: shipDH
    pointer:
      sourceName: drydock/aarch64_u16all
    seed:
      versionName: master

  - name: aarch64_u16cppall_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: dry-dock/aarch64_u16cppall
      branch: master

  - name: aarch64_u16cppall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: drydock/aarch64_u16cppall
    seed:
      versionName: master

  - name: aarch64_u16pytall_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: dry-dock/aarch64_u16pytall
      branch: master

  - name: aarch64_u16pytall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: drydock/aarch64_u16pytall
    seed:
      versionName: master

  - name: aarch64_u16javall_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: dry-dock/aarch64_u16javall
      branch: master

  - name: aarch64_u16javall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: drydock/aarch64_u16javall
    seed:
      versionName: master

  - name: aarch64_u16nodall_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: dry-dock/aarch64_u16nodall
      branch: master

  - name: aarch64_u16nodall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: drydock/aarch64_u16nodall
    seed:
      versionName: master

  - name: aarch64_u16pyt_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: dry-dock/aarch64_u16pyt
      branch: master

  - name: aarch64_u16pyt_img
    type: image
    integration: shipDH
    pointer:
      sourceName: drydock/aarch64_u16pyt
    seed:
      versionName: master

  - name: aarch64_u16cpp_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: dry-dock/aarch64_u16cpp
      branch: master

  - name: aarch64_u16cpp_img
    type: image
    integration: shipDH
    pointer:
      sourceName: drydock/aarch64_u16cpp
    seed:
      versionName: master

  - name: aarch64_u16microbase_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: dry-dock/aarch64_u16microbase
      branch: master

  - name: aarch64_u16microbase_img
    type: image
    integration: shipDH
    pointer:
      sourceName: drydock/aarch64_u16microbase
    seed:
      versionName: master

jobs:
  - name: aarch_64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch64_u16_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildImage.sh aarch64 aarch64_u16 aarch_64_Ubuntu_16_04_prep
            - popd
      - OUT: aarch64_u16_img

  - name: all_aarch_64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch64_u16_img
      - IN: aarch64_u16all_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildImage.sh aarch64 aarch64_u16all all_aarch_64_Ubuntu_16_04_prep
            - docker run drydock/aarch64_u16all:master "/u16all/test/service_test.sh"
            - popd
      - OUT: aarch64_u16all_img

  - name: microbase_aarch_64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch64_u16_img
      - IN: aarch64_u16microbase_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildImage.sh aarch64 aarch64_u16microbase microbase_aarch_64_Ubuntu_16_04_prep
            - popd
      - OUT: aarch64_u16microbase_img

  - name: javall_aarch_64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch64_u16all_img
      - IN: aarch64_u16javall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildImage.sh aarch64 aarch64_u16javall javall_aarch_64_Ubuntu_16_04_prep
            - popd
      - OUT: aarch64_u16javall_img

  - name: nodall_aarch_64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch64_u16all_img
      - IN: aarch64_u16nodall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildImage.sh aarch64 aarch64_u16nodall nodall_aarch_64_Ubuntu_16_04_prep
            - popd
      - OUT: aarch64_u16nodall_img

  - name: pyt_aarch_64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch64_u16_img
      - IN: aarch64_u16pyt_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildImage.sh aarch64 aarch64_u16pyt pyt_aarch_64_Ubuntu_16_04_prep
            - popd
      - OUT: aarch64_u16pyt_img

  - name: cpp_aarch_64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch64_u16_img
      - IN: aarch64_u16cpp_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildImage.sh aarch64 aarch64_u16cpp cpp_aarch_64_Ubuntu_16_04_prep
            - popd
      - OUT: aarch64_u16cpp_img

  - name: cppall_aarch_64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch64_u16all_img
      - IN: aarch64_u16cppall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildImage.sh aarch64 aarch64_u16cppall cppall_aarch_64_Ubuntu_16_04_prep
            - popd
      - OUT: aarch64_u16cppall_img

  - name: pytall_aarch_64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch64_u16all_img
      - IN: aarch64_u16pytall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildImage.sh aarch64 aarch64_u16pytall pytall_aarch_64_Ubuntu_16_04_prep
            - popd
      - OUT: aarch64_u16pytall_img

  - name: reqExec_aarch64_Ubuntu_16_04_pack
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      # pip fails while installing pyinstaller, while running in a container.
      # so, running this job on host
      container: false
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_bits_access_cli
        switch: off
      - IN: aarch64_u16microbase_img
      - IN: aarch_reqExec_repo
      - TASK:
          name: install awscli
          script:
            - export LC_ALL=C
            - pip install awscli==1.11.91
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildAndPushReqExecArtifacts.sh aarch_reqExec_repo
            - popd

  - name: reports_aarch64_Ubuntu_16_04_pack
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: aarch_64_Ubuntu_16_04_prep_repo
        switch: off
      - IN: aarch_bits_access_cli
        switch: off
      # Reports are unlikely to change too often, so manually build when required.
      - IN: aarch_64_micro_repo
        switch: off
      - TASK:
          runtime:
            # Use aarch64/Ubuntu_16.04 image and pool if/when it becomes available.
            # Since Go can cross-compile, use a x86_64 image,
            options:
              imageName: drydock/u16golall
              imageTag: v6.1.4
          script:
            # Note: gvm doesn't seem to load automatically, so add it to the PATH manually.
            # Remove this if its not needed anymore.
            - PATH="$PATH:/root/.gvm/gos/go1.9.2/bin"
            - pushd $(shipctl get_resource_state "aarch_64_Ubuntu_16_04_prep_repo")
            - ./buildAndPushReportsArtifacts.sh aarch_64_micro_repo
            - popd

  - name: reqProc_aarch64_Ubuntu_16_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: aarch_bits_ecr_cli
        scopes:
          - ecr
        switch: off
      - IN: aarch_dh_cli
        switch: off
      - IN: aarch_reqProc_repo
      - IN: reqExec_x86_64_Ubuntu_14_04_pack
      - IN: reqExec_x86_64_Ubuntu_16_04_pack
      - IN: reqExec_x86_64_CentOS_7_pack
      - IN: reqExec_x86_64_macOS_10_12_pack
      - IN: reqExec_aarch64_Ubuntu_16_04_pack
      - IN: aarch_execTemplates_repo
      - IN: aarch64_u16microbase_img
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "aarch_reqProc_repo")
            - ./build.sh aarch64 Ubuntu_16.04 drydock aarch64_reqproc
            - popd
